services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: kafka_tutorials_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - app/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
